In [3]:
test = "Hello Numpy";
print(test);

Hello Numpy


In [4]:
import numpy as np

In [6]:
one_dimensional_array = np.array([1, 2, 3]);
print(one_dimensional_array);



[1 2 3]


In [15]:
# Create an array with 5 integers, starting from the default integer 0.
b = np.arange(5);
print(b);

[0 1 2 3 4]


In [14]:
# Create an array that starts from the integer 5, ends at 30, incremented by 5.
c = np.arange(5, 30, 5);
print(c);

[ 5 10 15 20 25]


In [24]:
lin_spaced_arr = np.linspace(0, 100, 5, dtype=int);
lin_spaced_arr_float = np.linspace(0, 100, 5);
print(lin_spaced_arr);
print(lin_spaced_arr.dtype);
print(lin_spaced_arr_float);
print(lin_spaced_arr_float.dtype);

[  0  25  50  75 100]
int64
[  0.  25.  50.  75. 100.]
float64


In [29]:
# <U15 - 15 here shows the count of the characters of string which is 30 there
char_array = np.array(["I'll crush Machine Learning!!!"]);
print(char_array);
print(char_array.dtype);

["I'll crush Machine Learning!!!"]
<U30


In [52]:
# Return a new array of shape 5, filled with ones. by default dtype=float
ones_array = np.ones(5, dtype=int);
print(ones_array);

# Return a new array of shape 5, filled with zeros. by default dtype=float
zeros_array = np.zeros(5, dtype=int);
print(zeros_array);

# Return a new uninitialzied array of shape 3.
empty_array = np.empty(5, dtype=int);
print(empty_array);

# Returns a new array with values chosen at random
# Return a new array of shape 3 with random numbers between 0 and 1.
# Always float by default
rand_array = np.random.rand(3);
rand_array_int = np.random.randint(0, 100, 5, dtype=int);
print(rand_array);
print(rand_array_int);


[1 1 1 1 1]
[0 0 0 0 0]
[0 0 0 0 0]
[0.16594062 0.37300964 0.92911481]
[12 90 16 63 35]


**Multi Dimensional Arrays**

In [53]:
# Create a 2 dimensional array (2-D)
two_dim_array = np.array([[1, 2, 3], [4, 5, 6]]);
print(two_dim_array);

[[1 2 3]
 [4 5 6]]


In [54]:
# Alternative way of creating multidimensional array is to reshape 1D array.
# Using mp.reshape() - method

#1-D array
one_dim_array = np.array([1, 2, 3, 4, 5, 6]);

# Multidimensional array using reshape()
multi_dim_arr = np.reshape(
    one_dim_array, # the array to be reshaped
     (2, 3) # dimensions of the new array
);

print(multi_dim_arr);

[[1 2 3]
 [4 5 6]]


**Finding size, shape, and dimension**

In [57]:
# Dimension of the 2-D array multi_dim_arr
print(multi_dim_arr.ndim);


# Shape of the 2-D array multi_dim_arr
# Returns shape of 2 rows and 3 columns
print(multi_dim_arr.shape);

# Size of the array multi_dim_arr
# Returns total number of elements
print(multi_dim_arr.size);

2
(2, 3)
6


**Array math operations**

In [60]:
arr_1 = np.array([2, 4, 6]);
arr_2 = np.array([1, 3, 5]);

# Adding twp 1-D arrays

addition = arr_1 + arr_2;
print(addition);

# Subtracting two 1-D arrays
subtraction = arr_1 - arr_2;
print(subtraction);

# Multiplying two 1-D arrays elementwise
multiplication = arr_1 * arr_2;
print(multiplication);

# Dividing two 1-D arrays elementwise
division = arr_1 / arr_2;
print(division);

[ 3  7 11]
[1 1 1]
[ 2 12 30]
[2.         1.33333333 1.2       ]


In [62]:
# Broadcasting
vector = np.array([1, 2]);
vector * 1.6
print(vector*1.6)

[1.6 3.2]


**Indexing**

In [64]:
# Select the third element of the array. Remember the counting starts from 0.
a = ([1, 2, 3, 4, 5])
print(a[2])

# Select the first element of the array.
print(a[0])

# Indexing on a 2-D array
two_dim = np.array(([1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]))

# Select element number 8 from the 2-D array using indices i, j.
print(two_dim[2][1])

3
1
8


**Slicing**

In [66]:
# Slice the array a to get the array [2,3,4]
sliced_arr = a[1:4]
print(sliced_arr)

[2, 3, 4]


In [67]:
# Slice the array to get the array [1, 2, 3]
sliced_arr = a[:3];
print(sliced_arr)

[1, 2, 3]


In [70]:
# Slice the array to get the array [1, 3, 5]
sliced_arr = a[::2]
print(sliced_arr)

[1, 3, 5]


In [71]:
# Note that a == a[:] == a[::]
print(a == a[:] == a[::])

True


In [72]:
print(a is a[:])

False


In [73]:
print(a == a[:] == a[::])

True


In [80]:
# Let's slice the two_dim array to get the first row
print(two_dim_array)
sliced_arr_two_dim = two_dim_array[:1]
print(sliced_arr_two_dim)

[[1 2 3]
 [4 5 6]]
[[1 2 3]]


In [81]:
# Similarily, slice the two_dim array to get the last two rows
sliced_two_dim_rows = two_dim[1:3]
print(sliced_two_dim_rows)

[[4 5 6]
 [7 8 9]]


In [82]:
sliced_two_dim_rows = two_dim[:, 1]
print(sliced_two_dim_rows)

[2 5 8]


**Stacking**

In [88]:
a1 = np.array([[1,1], [2,2]]);
a2 = np.array([[3,3], [4,4]]);

print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

# Stack the array vertically
vert_stack = np.vstack((a1, a2))
print('--------------')
print(vert_stack)

# Stack the arrays horizontally
horz_stack = np.hstack((a1, a2))
print('--------------')
print(horz_stack)

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]
--------------
[[1 1]
 [2 2]
 [3 3]
 [4 4]]
--------------
[[1 1 3 3]
 [2 2 4 4]]


**Exercise**