In [2]:
import numpy as np
import matplotlib.pyplot as plt



In [3]:
A = np.array([
    [-1, 3],
    [3, 2]
],dtype=np.dtype(float))

b = np.array([7, 1] ,dtype=np.dtype(float))

print("Matrix A:");
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[-1.  3.]
 [ 3.  2.]]

Array b:
[7. 1.]


In [4]:
print(f"Shape of A: {A.shape}")
print(f"Shape of b: {b.shape}")

Shape of A: (2, 2)
Shape of b: (2,)


In [5]:
# Solving systems of linear equation with linalg
x = np.linalg.solve(A, b);
print(f"Solution: {x}");

Solution: [-1.  2.]


In [11]:
# Calculating the determinant of matrix with linalg.det
d = np.linalg.det(A);
print(f"Determinant of matrix A: {d:.2f}");

Determinant of matrix A: -11.00


In [16]:
A_system = np.hstack((A, b.reshape((2, 1))))
print(A_system)
print("------------------")
print(A_system[1])

[[-1.  3.  7.]
 [ 3.  2.  1.]]
------------------
[3. 2. 1.]


In [17]:
# System of linear equation with no solutions
A_2 = np.array ([
    [-1, 3],
    [3, -9]
], dtype=np.dtype(float))
b_2 = np.array([7, 1], dtype=np.dtype(float))
d_2 = np.linalg.det(A_2)

print(f"Determinant of matrix A_2: {d_2:.2f}")

Determinant of matrix A_2: 0.00


In [18]:
# Checking the singularity , non-singularity
try:
    x_2 = np.linalg.solve(A_2, b_2)
except np.linalg.LinAlgError as err:
    print(err)

Singular matrix


In [19]:
A_2_system = np.hstack((A_2, b_2.reshape((2, 1))))
print(A_2_system)

[[-1.  3.  7.]
 [ 3. -9.  1.]]


**System of Linear Equations with an Infinite Number of Solutions**

In [20]:
b_3 = np.array([7, -21], dtype=np.dtype(float))
A_3_system = np.hstack(((A_2, b_3.reshape(2, 1))))
print(A_3_system)

[[ -1.   3.   7.]
 [  3.  -9. -21.]]
