**Vector Creation & Basics**

In [1]:
import numpy as np

In [3]:
#1 D row-like vector
a_1d = np.array([2, 4, -1]);
print("a_1d:", a_1d);
print("Shape of a_1d:", a_1d.shape);

# 2D column vector
a_col = np.array([[2], [4], [-1]]);
print("\na_col:\n", a_col)
print("Shape of a_col:", a_col.shape)

a_1d: [ 2  4 -1]
Shape of a_1d: (3,)

a_col:
 [[ 2]
 [ 4]
 [-1]]
Shape of a_col: (3, 1)


In [4]:
# Transpose
print("Transpose of a_1d (no effect):", a_1d.T)
print("Transpose of a_col (no effect):", a_col.T)

Transpose of a_1d (no effect): [ 2  4 -1]
Transpose of a_col (no effect): [[ 2  4 -1]]


**Vector as Matrix Rows/Cols**

In [5]:
# Create two column vectors
v1 = np.array([[3], [1]]);
v2 = np.array([[2], [5]]);

# Check shapes
print("v1 shape:", v1.shape);
print("v2 shape:", v2.shape);

# Matrix addition
print("v1 + v2:\n", v1 + v2);

# Scaling a vector
print("2 * v1:\n", 2 * v1);


v1 shape: (2, 1)
v2 shape: (2, 1)
v1 + v2:
 [[5]
 [6]]
2 * v1:
 [[6]
 [2]]


In [6]:
w1 = np.array([3, 1])     # (2,) shape
w2 = np.array([[3], [1]]) # (2,1) shape

print(w1);
print(w2);

[3 1]
[[3]
 [1]]


In [10]:
# Define two vectors
a = np.array([1, 3, -5])
b = np.array([4, -2, -1])

dot = 0;
for i in range(len(a)):
  dot += a[i] * b[i];


print("Manual dot product:", dot);

# Numpy method
print("Using np.dot:", np.dot(a, b));
print("Using @ operator:", a @ b ); # # Python 3.5+

Manual dot product: 3
Using np.dot: 3
Using @ operator: 3


In [16]:
a = np.array([[1], [2]])  # shape (2,1)
b = np.array([[3], [4]])  # shape (2,1)

print("a.T @ b:", a.T @ b)  # Gives scalar: 1*3 + 2*4 = 11
print("b.T @ a:", b.T @ a)  # same

print(np.linalg.norm(a))

# print(a @ b);
# This fails. Why? a is (2,1), b is (2,1) → mismatch for dot.

a.T @ b: [[11]]
b.T @ a: [[11]]
2.23606797749979


In [15]:
# Cosine similarity: cos(theta) = (a·b) / (||a|| * ||b||)
def cosine_similarity(a, b):
    dot = np.dot(a, b)
    norm_a = np.linalg.norm(a)
    norm_b = np.linalg.norm(b)
    return dot / (norm_a * norm_b)

a = np.array([1, 0])
b = np.array([0, 1])
print("Cosine similarity:", cosine_similarity(a, b))  # 0.0 → orthogonal


Cosine similarity: 0.0
